version: '3.8'

services:
  backend:
    build: ../backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/neko
      - JWT_SECRET=your_jwt_secret
      - GOOGLE_CLIENT_ID=your_google_client_id
      - GOOGLE_CLIENT_SECRET=your_google_client_secret
      - OPENWEATHER_API_KEY=your_openweathermap_api_key
      - TWILIO_SID=your_twilio_sid
      - TWILIO_AUTH_TOKEN=your_twilio_auth_token
      - TWILIO_PHONE_NUMBER=your_twilio_phone_number
      - OPENAI_API_KEY=your_openai_api_key
      - OPENROUTESERVICE_API_KEY=your_openrouteservice_api_key
      - TOMTOM_API_KEY=your_tomtom_api_key
    volumes:
      - ../backend:/app
    depends_on:
      - mongo

  asr:
    build: ../
    ports:
      - "5005:5005"
    volumes:
      - ../model-en:/model-en
    command: python asr_server.py

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: